version: '3.9'
name: mvn-multimodule-dockerized-dev

services:
  delivery:
    container_name: delivery
    image: delivery
    build:
      context: ../
      dockerfile: delivery/Dockerfile-dev-delivery
    ports:
      - "5000:8080"
      - "5001:5001"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - logging.level.org.springframework.web=DEBUG
      - logging.level.org.hibernate=DEBUG
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5001,server=y,suspend=n"
  store:
    container_name: store
    image: store
    build:
      context: ../
      dockerfile: store/Dockerfile-dev-store
    ports:
      - "5010:8080"
      - "5011:5001"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - logging.level.org.springframework.web=DEBUG
      - logging.level.org.hibernate=DEBUG
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:5001,server=y,suspend=n"
